# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e62df001a08b8b4b76f579c4bf08fb488d23ebaa6fcbe7921ebe8c2e51e3ddd0f68697ad2398bec9f871bc3f0131da8f43e6ee5e715b7c6632ec8e11f147d0e2

test:
  secret_key_base: 9b38cc6746c1a887d04342ad23cab32595752a8f4d76eb30dd802b1687b1414effbe37eace400e0da9ca1bb387f510160a8a0b99fdd2ae02e8207dc9c92595f4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
