# Set the host name for URL creation
SitemapGenerator::Sitemap.default_host = "http://vieclamvanphong.com"

SitemapGenerator::Sitemap.create do
  # Put links creation logic here.
  #
  # The root path '/' and sitemap index file are added automatically for you.
  # Links are added to the Sitemap in the order they are specified.
  #
  # Usage: add(path, options={})
  #        (default options are used if you don't specify)
  #
  # Defaults: :priority => 0.5, :changefreq => 'weekly',
  #           :lastmod => Time.now, :host => default_host
  #
  # Examples:
  #
  # Add '/articles'
  #
  #   add articles_path, :priority => 0.7, :changefreq => 'daily'
  #
  # Add all articles:
  #
  #   Article.find_each do |article|
  #     add article_path(article), :lastmod => article.updated_at
  #   end
  add '/viec-lam/Tat-ca-dia-diem'
  add '/viec-lam/TP-Ho-Chi-Minh'
  add '/viec-lam/Ha-Noi'
   add '/viec-lam/Da-Nang'
    add '/viec-lam/Can-Tho'
	 add '/viec-lam/Hai-Phong'
	  add '/viec-lam/Tat-ca-dia-diem'
	   add '/viec-lam/Binh-Duong'
	    add '/viec-lam/An-Giang'
		 add '/viec-lam/Ba-Ria-Vung-Tau' 
		 add '/viec-lam/Bac-Giang'
		  add '/viec-lam/Bac-Kan'
		   add '/viec-lam/Bac-Ninh'
		    add '/viec-lam/Bac-Lieu'
			 add '/viec-lam/Ben-Tre'
			  add '/viec-lam/Binh-Dinh'
			   add '/viec-lam/Binh-Phuoc'
			    add '/viec-lam/Binh-Thuan'
				 add '/viec-lam/Ca-Mau'
				  add '/viec-lam/Cao-Bang'
				   add '/viec-lam/Dak-Lak'
				    add '/viec-lam/Dak-Nong'
					 add '/viec-lam/Dien-Bien'
					  add '/viec-lam/Dong-Nai'
					   add '/viec-lam/Dong-Thap'
					    add '/viec-lam/Gia-Lai'
						 add '/viec-lam/Ha-Giang'
						  add '/viec-lam/Ha-Nam'
						   add '/viec-lam/Hai-Duong'
						    add '/viec-lam/Hau-Giang'
							 add '/viec-lam/Hoa-Binh'
							  add '/viec-lam/Hung-Yen'
							  add '/viec-lam/Khanh-Hoa'
							  add '/viec-lam/Kien-Giang'
							  add '/viec-lam/Kon-Tum'
							  add '/viec-lam/Lai-Chau'
							   add '/viec-lam/Lam-Dong'
							  add '/viec-lam/Lang-Son'
							  add '/viec-lam/Lao-Cai'
							  add '/viec-lam/Long-An'
							  add '/viec-lam/Nam-Dinh'
							   add '/viec-lam/Nghe-An'
							  add '/viec-lam/Ninh-Binh'
							  add '/viec-lam/Ninh-Thuan'
							  add '/viec-lam/Phu-Tho'
							  add '/viec-lam/Quang-Binh'
							   add '/viec-lam/Quang-Nam'
							  add '/viec-lam/Quang-Ngai'
							  add '/viec-lam/Quang-Ninh'
							  add '/viec-lam/Quang-Tri'
							  add '/viec-lam/Soc-Trang'
							     add '/viec-lam/Son-La'
							  add '/viec-lam/Tay-Ninh'
							  add '/viec-lam/Thai-Binh'
							  add '/viec-lam/Thai-Nguyen'
							  add '/viec-lam/Thanh Hóa'
							   add '/viec-lam/Thua-Thien-Hue'
							  add '/viec-lam/Tien-Giang'
							  add '/viec-lam/Tra-Vinh'
							  add '/viec-lam/Tuyen-Quang'
							  add '/viec-lam/Vinh-Long'
							   add '/viec-lam/Vinh-Phuc'
							  add '/viec-lam/Yen-Bai'
							  add '/viec-lam/Phu-Yen'
						add '/tim-viec-lam/Tat-ca-nghanh-nghe'
		add '/tim-viec-lam/An-toan-PCCC'
			add '/tim-viec-lam/Bao-hiem'
				add '/tim-viec-lam/Ban-hang'
add '/tim-viec-lam/Bao-chi'
add '/tim-viec-lam/Bao-ve'
add '/tim-viec-lam/Bat-đong-san'
add '/tim-viec-lam/Bien-phien-dich'
add '/tim-viec-lam/Chung-khoan'
add '/tim-viec-lam/Co-khi'
add '/tim-viec-lam/Cong-nghe-cao'
add '/tim-viec-lam/Cong-nghe-sinh-hoc'
add '/tim-viec-lam/Cham-soc-suc-khoe'
add '/tim-viec-lam/Dau-khi'
add '/tim-viec-lam/Det-may'
add '/tim-viec-lam/Da-giay'
add '/tim-viec-lam/Duoc-Pham'
add '/tim-viec-lam/Dich-vụ-khach-hang'
add '/tim-viec-lam/Du-an'
add '/tim-viec-lam/Du-lich'
add '/tim-viec-lam/Dien-Dien-tu'
add '/tim-viec-lam/Dao-tao-Giao-duc'
add '/tim-viec-lam/Hanh-chinh'
add '/tim-viec-lam/Khach-san'
add '/tim-viec-lam/Hoa-hoc-Hoa-sinh'
add '/tim-viec-lam/Kho-van'
add '/tim-viec-lam/Kien-truc'
add '/tim-viec-lam/Kinh-doanh'
add '/tim-viec-lam/Ke-toan'
add '/tim-viec-lam/Kiem-toan'
add '/tim-viec-lam/Giao-nhan'
add '/tim-viec-lam/Marketing'
add '/tim-viec-lam/Moi-truong'
add '/tim-viec-lam/My-thuat'
add '/tim-viec-lam/Ngan-hang'
add '/tim-viec-lam/Nong-nghiep'
add '/tim-viec-lam/Nhan-su'
add '/tim-viec-lam/Luat-su'
add '/tim-viec-lam/Hang-khong'
add '/tim-viec-lam/Lao-dong-pho-thong'
add '/tim-viec-lam/Lam-nghiep'
add '/tim-viec-lam/Lai-xe'
add '/tim-viec-lam/Internet-Online-Media'
add '/tim-viec-lam/IT-Phan-mem'
add '/tim-viec-lam/IT-Phan-cung-Mang'
add '/tim-viec-lam/O-to'
add '/tim-viec-lam/San-Xuat-Vat-tu'
add '/tim-viec-lam/Quang-cao'
add '/tim-viec-lam/QA-QC'
add '/tim-viec-lam/Thiet-ke'
add '/tim-viec-lam/Tu-van'
add '/tim-viec-lam/Thu-ky'
add '/tim-viec-lam/Tai-chinh'
add '/tim-viec-lam/Dau-tu'
add '/tim-viec-lam/Truyen-thong'
add '/tim-viec-lam/Chung-khoan'
add '/tim-viec-lam/Tap-vu'
add '/tim-viec-lam/Vien-Thong'
add '/tim-viec-lam/Van-chuyen'
add '/tim-viec-lam/Xay-dung'
add '/tim-viec-lam/Xuat-nhap-khau'
add '/tim-viec-lam/Y-te'
add '/tim-viec-lam/Khac'
						
  add '/viec-lam/'
   add '/contact_us'
  Vieclam.find_each do |vieclam|
    add vieclam_path(vieclam), :lastmod => vieclam.updated_at
	
  end
end
